# TODOs
- office/reflection.md:
  - description: No TODO markers left in reflection.md
    category: Reflection
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- office/reflection.md:
  - description: reflection.md checkboxes checked attested to
    category: Reflection
    check: MatchFileRegex
    options:
      regex: "\\-\\s\\[x\\]"
      count: 3
- north/Stoplight.py:
  - description: No TODO markers left in north/Stoplight.py
    category: Let there be Light (North)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- north-east/Stoplight.py:
  - description: No TODO markers left in north-east/Stoplight.py
    category: Let there be Light (North-East)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- north-west/Stoplight.py:
  - description: No TODO markers left in north-west/Stoplight.py
    category: Let there be Light (North-West)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- south/Stoplight.py:
  - description: No TODO markers left in south/Stoplight.py
    category: Let there be Light (South)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- south-west/Stoplight.py:
  - description: No TODO markers left in south-west/Stoplight.py
    category: Let there be Light (South-West)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- east/Stoplight.py:
  - description: No TODO markers left in east/Stoplight.py
    category: Let there be Light (East)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- west/Stoplight.py:
  - description: No TODO markers left in west/Stoplight.py
    category: Let there be Light (West)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- .bus:
  - description: No TODO markers left in Bus.py (wherever it ended up)
    category: The Public Transport Project (Bus)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- .car:
  - description: No TODO markers left in Car.py (wherever it ended up)
    category: The Private Transport Project (Car)
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
# Events
- description: Bus has traveled (is no longer in main folder)
  category: The Public Transport Project (Bus)
  check: MatchCommandFragment
  options:
    command: find Bus.py
    fragment: "Bus.py"
    count: 0
    exact: true
- description: Car has traveled (is no longer in main folder)
  category: The Private Transport Project (Car)
  check: MatchCommandFragment
  options:
    command: find Car.py
    fragment: "Car.py"
    count: 0
    exact: true
# Code cops
- north/Stoplight.py:
  - description: north/Stoplight.py contains at least two if statements for the light variable
    category: Let there be Light (North)
    check: MatchFileRegex
    options:
      regex: "(el)?if\\slight\\s=="
      count: 2
- south-west/Stoplight.py:
  - description: south-west/Stoplight.py contains at least two if statements for the crosswalk variable
    category: Let there be Light (South-West)
    check: MatchFileRegex
    options:
      regex: "(el)?if\\scrosswalk\\s=="
      count: 1
- south/Stoplight.py:
  - description: south/Stoplight.py contains at least two if statements for the light variable
    category: Let there be Light (South)
    check: MatchFileRegex
    options:
      regex: "(el)?if\\slight\\s=="
      count: 2
- east/Stoplight.py:
  - description: east/Stoplight.py contains at least two if statements for the light variable
    category: Let there be Light (East)
    check: MatchFileRegex
    options:
      regex: "(el)?if\\slight\\s=="
      count: 2
- east/Stoplight.py:
  - description: east/Stoplight.py accounts for the turn signal
    category: Let there be Light (East)
    check: MatchFileRegex
    options:
      regex: "and\\s(not)?\\sturn"
      count: 3
- east/Stoplight.py:
  - description: east/Stoplight.py accounts for the hold between signals
    category: Let there be Light (East)
    check: MatchFileRegex
    options:
      regex: "and\\s(not\\s)?hold"
      count: 1
- west/Stoplight.py:
  - description: west/Stoplight.py accounts for the timeout between signals
    category: Let there be Light (West)
    check: MatchFileRegex
    options:
      regex: "and\\s(not\\s)?timeout"
      count: 1
- west/Stoplight.py:
  - description: west/Stoplight.py contains at least two if statements for the light variable
    category: Let there be Light (West)
    check: MatchFileRegex
    options:
      regex: "(el)?if\\slight\\s=="
      count: 2
- north-west/Stoplight.py:
  - description: north-west/Stoplight.py contains the light variable in conditional statements
    category: Let there be Light (North-West)
    check: MatchFileRegex
    options:
      regex: "light\\s=="
      count: 3
- north-west/Stoplight.py:
  - description: north-west/Stoplight.py sets the crosswalk variable
    category: Let there be Light (North-West)
    check: MatchFileRegex
    options:
      regex: "crosswalk\\s="
      count: 4
- north-east/Stoplight.py:
  - description: north-east/Stoplight.py contains the light variable in conditional statements
    category: Let there be Light (North-East)
    check: MatchFileRegex
    options:
      regex: "light\\s=="
      count: 2
- north-east/Stoplight.py:
  - description: north-east/Stoplight.py contains the people_waiting variable in conditional statements
    category: Let there be Light (North-East)
    check: MatchFileRegex
    options:
      regex: "people_waiting\\s>"
      count: 2
- south-east/Stoplight.py:
  - description: north-east/Stoplight.py sets the crosswalk variable
    category: Let there be Light (South-East)
    check: MatchFileRegex
    options:
      regex: "crosswalk\\s="
      count: 4
- south-east/Stoplight.py:
  - description: north-east/Stoplight.py uses the countdown variable in conditional statements
    category: Let there be Light (South-East)
    check: MatchFileRegex
    options:
      regex: "countdown\\s>"
      count: 3
- south-east/Stoplight.py:
  - description: north-east/Stoplight.py uses the light variable in conditional statements
    category: Let there be Light (South-East)
    check: MatchFileRegex
    options:
      regex: "light\\s=="
      count: 2
- .bus:
  - description: Bus.py (wherever it is) uses a while statement
    category: The Public Transport Project
    check: MatchFileRegex
    options:
      regex: "while\\sstoplight"
      count: 1
- .car:
  - description: Car.py (where'd it go?) uses at least two if statements for the signal variable
    category: The Private Transport Project
    check: MatchFileRegex
    options:
      regex: "(el)?if\\ssignal\\s=="
      count: 2
